name: GCP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Retrieve GCP Key Path
      run: echo "GCP_CREDENTIALS=${{ secrets.GCP_CREDENTIALS }}" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-app:latest -f ./app/Dockerfile .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-app:latest

    - name: Terraform Init
      run: cd terraform && terraform init

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve -var="gcp_key_path=${{ env.GCP_CREDENTIALS }}"
